baseURL: /
languageCode: en-us
title: Rekor
theme: hugo-fresh
publishDir: "docs"
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

# Enable for syntax highlighting
pygmentsUseClasses: true
pygmentsCodeFences: true
disableKinds: ["taxonomy", "taxonomyTerm", "section"]

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/rekor-logo.png
    link: /
  font:
    name: "Catamaran"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Project Rekor
    # Hero subtitle (optional)
    subtitle: A Cryptographic, immutable, append only transparency log
    # Button text
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "/get_started/"
    # Hero image (from static/images/___)
    image: illustrations/rekor-logo-symbol-github.png
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Community
    url: https://github.com/projectrekor
  - title: OpenAPI Spec
    url: https://rekor.dev/swagger
    # button: true
  - title: Get Started
    sublinks:
    - title: Rekor Client
      url: /get_started/client/
    - title: Rekor Server
      url: /get_started/server/
  - title: Documentation
    sublinks:
    - title: Develop a Rekor API Client
      url: /docs/api_example/
    - title: Plugable types
      url: /docs/plugable_types/
  - title: Rekor Directory
    url: /rekor_directory
  - title: FAQ
    url: /faq/
  # section1:
  #   title: Current Users of Rekor
  #   subtitle: example projects
  #   tiles:
  #   - title: Acme Project
  #     icon: mouse-globe
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Find out more
  #   - title: Another Project
  #     icon: laptop-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Find out more
  #   - title: Add-ons & plugins
  #     icon: plug-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Find out more
  # # section2:
  #   title: What can rekor provide
  #   subtitle:
  #   features:
  #   - title: Production grade backend
  #     text: Rekor uses the certificate transparency project trillian as a cryptographic datastore. Trillian is production hardended software
  #     # Icon (from /images/illustrations/icons/___.svg)
  #     icon: laptop-cloud
  #   - title: Mutliple Formats
  #     text: Rekor supports many existing formats such as SBOM, In-toto as well as the standard generic rekord type used by projects such as node.js, kernel
  #     icon: doc-sync
  #   - title: OpenAPI
  #     text: We have an openapi, you should use it.
  #     icon: mobile-feed
  section3:
    title: Integrate with Rekors API's
    subtitle: Learn how to use Rekor as part of your app eco-system
    image: illustrations/mockups/app-mockup.png
    buttonText: Learn More
    buttonLink: "/get_started/"
  section4:
    title: Current users of Rekor
    subtitle: User testimonials
    clients:
    - name: Irma Walters
      quote: As a community rekor has provided a transparent way of logging are software releases of the Acme Framework for our users.
      job: OSS project, Maintainer
      img: 1
    - name: John Bradley
      quote: We monitor rekor for activities that might suggest someone misusing our namespace or release signing keys.
      job: Developer, Super Security LTD
      img: 2
    - name: Gary Blackman
      quote: We run our own internal Rekor instance which has helped us meet the strict compilance needs of our customers.
      job: Cloud Engineer @ Big Cloud Inc
      img: 3
  # section5: true
  # footer:
  #   # Logo (from /images/logos/___)
  #   logo: rekor-logo.png
  #   # Social Media Title
  #   socialmediatitle: Follow Us
  #   # Social media links (GitHub, Twitter, etc.). All are optional.
  #   socialmedia:
  #   - link: https://github.com/projectrekor
  #     # Icons are from Font Awesome
  #     icon: github
  #   # - link: https://dribbble.com/#
  #   #   icon: dribbble
  #   # - link: https://facebook.com/#
  #   #   icon: facebook
  #   - link: #
  #     icon: twitter
  #   # - link: https://bitbucket.org/#
  #   #   icon: bitbucket
  #   bulmalogo: false
  #   quicklinks:
  #     column1:
  #       title: "Placeholder 1"
  #       links:
  #       - text: Discover features
  #         link: /
  #       - text: Why choose our product?
  #         link: /
  #       - text: Compare features
  #         link: /
  #       - text: Our roadmap
  #         link: /
  #       - text: AGB
  #         link: /agb
  #     column2:
  #       title: "Placeholder 2"
  #       links:
  #       - text: Get started
  #         link: /
  #       - text: User guides
  #         link: /
  #       - text: Admin guide
  #         link: /
  #       - text: Developers
  #         link: /
  #     column3:
  #       title: "Placeholder 3"
  #       links:
  #       - text: Latest news
  #         link: /blog/first
  #       - text: Tech articles
  #         link: /blog/second
